### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by bixiaopeng0** [Xiangyu-CAS/AICity2020-VOC-ReID#10]
请问数据集有网盘链接吗？
我看aicity官网还要输入秘钥才给下载

**Comment by Xiangyu-CAS** [comment]
你好,数据集需要签署不散播和非商业用途协议才能获取,填写agreement并发送后组委会就会提供秘钥了. 因此我们也不能随便散播数据.....

**Comment by bixiaopeng0** [comment]
谢谢回复
