### ISSUE TITLE
一个有关于weakly_supervised_crop_aug.py的问题

### ISSUE THREAD

**Issue by okzhili** [Xiangyu-CAS/AICity2020-VOC-ReID#11]
感谢作者开源如此优秀的代码，但是有个问题一直困扰着我
fm[0:4, :] = 0
fm[12:16, :] = 0
fm[:, 0:4] = 0
fm[:, 12:16] = 0
在weakly_supervised_crop_aug.py文件中这几行代码的作用是什么呢，这个需要根据特征图大小来修改吗？

**Comment by Xiangyu-CAS** [comment]
额...这个是临时加上去的,用cityflow的数据训练出来的模型,因为存在尺度问题,所以feature map会激活边角四个点,这时候crop会把边角给框进去,导致crop出来不准,所以我人为给它设置为0了.用veri和market1501这些数据集训练出来的feature map边角就不会被激活.
