### ISSUE TITLE
复现

### ISSUE THREAD

**Issue by bixiaopeng0** [Xiangyu-CAS/AICity2020-VOC-ReID#12]
你好，我在训练veri数据集时，用的log日志里的参数，只复现到了80.7，比日志差0.9个点

- 请问81.6在训练时用到了弱监督增强了吗？
- 训练0.9个点的偏差正常吗？

**Comment by Xiangyu-CAS** [comment]
1. 没有用弱监督增强，因为veri已经crop很紧致了，这点你从训练batch数量可以看出来
2. 公共数据集的训练结果一般比较稳定，很少偏差0.9%，至于你是什么原因就不清楚了....

**Comment by bixiaopeng0** [comment]
谢谢回复
