### ISSUE TITLE
BN层问题

### ISSUE THREAD

**Issue by bixiaopeng0** [Xiangyu-CAS/AICity2020-VOC-ReID#13]
大佬，我又来了，能留个邮箱或wx吗？
reid-strong-baseline 里面triplet loss和ID loss由BN层隔开,分别用了不同的feature
在你代码里用的是同一个feature，请问这个地方你是怎么考虑的？

**Comment by Xiangyu-CAS** [comment]
reid-strong-baseline用BN把triplet loss和ID loss隔开的考虑主要是两个loss优化尺度不一致，放在一起可能导致坍缩到一个点，训练mAP=0.0%，使用margin softmax loss（arcface，circle）后就不会产生这样的问题，因为margin softmax loss对特征和权重做了L2 norm。

我把id loss和triplet loss挪到一块，在aicity上大概能好1%，看起来也更自然。这个同数据集有关，是否隔开最终影响不会特别大。

邮箱是zhuxiangyu@ruiyanai.com, wx：z398766201

**Comment by bixiaopeng0** [comment]
谢谢回复
