### ISSUE TITLE
训练Orientation ReID和Camera ReID分支的数据集设置

### ISSUE THREAD

**Issue by LishaTang** [Xiangyu-CAS/AICity2020-VOC-ReID#14]
您好，请问下您在训练Orientation ReID和Camera ReID分支的时候数据集aicity20-ReOri/ 和aicity20-ReCam/ 是如何设置的呢？谢谢！

**Comment by Xiangyu-CAS** [comment]
你好，直接使用这个数据集就可以，https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/master/lib/data/datasets/aicity20_ReCam.py，
相比aicity20，唯一区别就是把pid和camid换了位置，训练脚本参考https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/master/scripts/aicity20/ReCamID.sh

**Comment by include-1main2object** [comment]
谢谢回复
