### ISSUE TITLE
关于图片的crop

### ISSUE THREAD

**Issue by jiyidefeng1990** [Xiangyu-CAS/AICity2020-VOC-ReID#15]
Hi，很棒的工程！有个问题请教下，制作数据集AIC20_ReID_Cropped时，需要用到0326-search/augmix/best.pth，这个模型应该去哪里下载呢，一直没有找到哎，求帮忙

**Comment by Xiangyu-CAS** [comment]
你好，这个模型是一个初始模型，用AIC20_ReID数据集训练的，之前我不小心删掉了，我重新训练了一个，并且上传到google drive了，具体可以查看 https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/commit/82d432b78853b6b863781b0a5702dfb378ac7abd

**Comment by jiyidefeng1990** [comment]
嗯嗯，明白了，非常感谢！！
