### ISSUE TITLE
关于工程中的数据集

### ISSUE THREAD

**Issue by jiyidefeng1990** [Xiangyu-CAS/AICity2020-VOC-ReID#16]
Hello~项目已经成功跑起来了，识别效果很棒！还有个小问题想请教下您，
在运行的时候，数据集中有AIC20_REID,AIC20_REID_Cropped，和AIC20_ReID_Simulation，AIC20_REID中又有image_train,image_query,image_test,
我想问下，如果只提供AIC20_REID，然后其内部仅有image_test和image_query，没有image_train，可以识别出image_test中与image_query对应的汽车图片吗？因为我这样运行后，会报image_train中数据找不到的错误，不知道是否可以通过改动代码来实现这种需求，还是说算法本身并不支持这样做，必须要有image_train文件夹

**Comment by Xiangyu-CAS** [comment]
您好，测试的时候是不需要image_train的，改动数据集文件即可，https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/82d432b78853b6b863781b0a5702dfb378ac7abd/lib/data/datasets/aicity20.py#L43 注释掉这行就好。

**Comment by jiyidefeng1990** [comment]
嗯嗯，如果改动代码的话
1.是只提供AIC20_REID就可以，AIC20_REID_Cropped，和AIC20_ReID_Simulation都可以不要吗？
2. AIC20_REID中只提供image_test和image_query就行吗？这个文件夹内部的其他的文件比如name_query.txt，train_label.xml，test_track.txt之类的文件也都不需要吗？

**Comment by Xiangyu-CAS** [comment]
AIC20_REID， AIC20_REID_Cropped， AIC20_ReID_Simulation三个测试集都是训练用的，测试的时候随便你怎么组织，如果不量化测试mAP性能，只输出top-k的匹配结果的话，随便你怎么组织，只需要query图片和gallery图片就可以，pid和camid都可以设置为1

**Comment by jiyidefeng1990** [comment]
了解了，非常感谢！
