### ISSUE TITLE
Results on VeRi-776

### ISSUE THREAD

**Issue by ming1993li** [Xiangyu-CAS/AICity2020-VOC-ReID#17]
Hi, could you please clarify whether the results on VeRi-776 in your paper are obtained using image-to-track or image-to-image test fashion?

**Comment by Xiangyu-CAS** [comment]
Hi， results on VeRi are tested without image-to-track

**Comment by ming1993li** [comment]
So, you got mAP 81.6% adopting RECT-Net with image-to-image test setting on VeRi-776, is that right?

**Comment by Xiangyu-CAS** [comment]
That's right, you can refer to training [log](https://drive.google.com/file/d/1MAErCPplveRmwaVnxBCvXM2wkiUSrpKd/view) for detail, it's tested without any post-processing tricks.

**Comment by ming1993li** [comment]
Thank you so much!
