### ISSUE TITLE
关于车辆向量的获取

### ISSUE THREAD

**Issue by jiyidefeng1990** [Xiangyu-CAS/AICity2020-VOC-ReID#18]
您好，打扰一下，请教您一个问题，如果我只想拿到车辆最终的表示向量，可不可以不去计算向量间的dist?就是说，给我一张车辆的图片，我就直接获取这个车辆的表示向量？

**Comment by Xiangyu-CAS** [comment]
https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/82d432b78853b6b863781b0a5702dfb378ac7abd/lib/engine/inference.py#L30
在test的时候，从inference里面直接取出来就可以

**Comment by jiyidefeng1990** [comment]
ReCamID时会得到一个feat.npy，ReOriID时也会得到一个feat.npy，利用他们两个产生的feat_distmat.npy,再加上next101-320-circle ，r101-320-circle和 r50-320-circle这三个模型，又可以得到三个不同的feat.npy,您觉得在车辆重识别方面，哪个模型获取的车辆表示向量最为准确，或者怎么样对这些feats.npy进行处理最为合适

**Comment by jiyidefeng1990** [comment]
ReCamID时会得到一个feat.npy，ReOriID时也会得到一个feat.npy，利用他们两个产生的feat_distmat.npy,再加上next101-320-circle ，r101-320-circle和 r50-320-circle这三个模型，又可以得到三个不同的feat.npy,您觉得在车辆重识别方面，哪个模型获取的车辆表示向量最为准确，或者怎么样对这些feats.npy进行处理最为合适

**Comment by jiyidefeng1990** [comment]
ReCamID时会得到一个feat.npy，ReOriID时也会得到一个feat.npy，利用他们两个产生的feat_distmat.npy,再加上next101-320-circle ，r101-320-circle和 r50-320-circle这三个模型，又可以得到三个不同的feat.npy,您觉得在车辆重识别方面，哪个模型获取的车辆表示向量最为准确，或者怎么样对这些feats.npy进行处理最为合适

**Comment by Xiangyu-CAS** [comment]
next101-320-circle ，r101-320-circle和 r50-320-circle，三个模型都是用来做车辆ReID的，这里三个模型性能差不多，r101性能最高，ReCamID，ReOriID是用来辅助提高车辆ReID性能的，最终的表达式是 (r50+r101+next101) / 3 - 0.1 * ReCamID - 0.1 * ReOriID，单独取r50，r101，next101中的任意一个也都是可以使用的

**Comment by jiyidefeng1990** [comment]
感谢您的回复，还有个小问题，为了获取车辆的向量，总是需要用image_quey和image_test两个数据集，通过ReID和ReOriID得到feat_distmat.npy，之后才能再通过（next101-320-circle ，r101-320-circle或者 r50-320-circle）计算最终的feats.npy。有没有可能，只给出一个数据集，就获得最终每个车辆的表示向量？

**Comment by jiyidefeng1990** [comment]
感谢您的回复，还有个小问题，为了获取车辆的向量，总是需要用image_quey和image_test两个数据集，通过ReID和ReOriID得到feat_distmat.npy，之后才能再通过（next101-320-circle ，r101-320-circle或者 r50-320-circle）计算最终的feats.npy。有没有可能，只给出一个数据集，就获得最终每个车辆的表示向量？

**Comment by Xiangyu-CAS** [comment]
image_query和image_test两个数据集是分别作为query和gallery，在计算feat的时候其实是合并到一起，计算完再分开的。
https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/82d432b78853b6b863781b0a5702dfb378ac7abd/lib/data/build.py#L83
你把上述代码的地方修改一下，输入变为你想要的输入就可以了，这是工程上改代码的问题，跟着数据流来修改就可以，哪里报错改哪里

**Comment by jiyidefeng1990** [comment]
您说这个ReCam和ReORiID都是用来辅助的，那是不是说要获得汽车向量的话，不用这两个模型，单独只用101那个就够进行区分了呢？

**Comment by Xiangyu-CAS** [comment]
是的没错

**Comment by jiyidefeng1990** [comment]
明白了，非常感谢！
