### ISSUE TITLE
feats.npy File

### ISSUE THREAD

**Issue by Paulamde** [Xiangyu-CAS/AICity2020-VOC-ReID#19]
Hello,

If we just want to reproduce the result on AICity 2020 Challenge of your code, I have downloaded the pretrained model 0409-ensemble but i get the error that I do not have the file feats.npy. ¿Should this file be in the pretrained folder 0409-ensemble?

Thanks

**Comment by Xiangyu-CAS** [comment]
Hi, you need to generate features by runing models first,  Refer to [scripts](https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/master/scripts/aicity20/submit.sh)
