### ISSUE TITLE
how to generate the dataset_aug_dir?

### ISSUE THREAD

**Issue by Zhanghao5200** [Xiangyu-CAS/AICity2020-VOC-ReID#20]
I can't find the code of the generation of augment dataset,so I don't have ''AIC20_ReID_Cropped" directory.Can you help me?

**Comment by Xiangyu-CAS** [comment]
@Zhanghao5200 Good day to you.  Maybe you can refer to 'AICTIY2020.md'? Follow "prepare_data: step2: use inital model to crop vehicles".

**Comment by Zhanghao5200** [comment]
> @Zhanghao5200 Good day to you. Maybe you can refer to 'AICTIY2020.md'? Follow "prepare_data: step2: use inital model to crop vehicles".

Thanks!But there is a new error"AIC20_ReID_Cropped/image_query/000001.jpg does not exist".How to solve this problem?

**Comment by vokhidovhusan** [comment]
@Xiangyu-CAS 
I have arranged data folder as following:
data/ReID/Vehicle/AIC20_ReID
data/ReID/Vehicle/AIC20_ReID_Simulation

And when I run the first step in `DataPreparation` I got following error.
RuntimeError: '/home/username/data/ReID/Vehicle/VeRi' is not available

@Xiangyu-CAS @Zhanghao5200 How could be solved this problem?

**Comment by vokhidovhusan** [comment]
@Xiangyu-CAS I have followed `prepare_data: step2`. I only can cropped image_train data. But it gives errors for cropping `image_query` data

OSError: /home/username/projects/re-id/2nd-aicity2020_vehicle_re-id/data/ReID/Vehicle/AIC20_ReID_Cropped/image_query/000001.jpg does not exist

**Comment by vokhidovhusan** [comment]
@Xiangyu-CAS @Zhanghao5200 
Ok guys. I managed to crop all query, test, train images

**Comment by Xiangyu-CAS** [comment]
> @Xiangyu-CAS @Zhanghao5200
> Ok guys. I managed to crop all query, test, train images

Good to hear that : )
