### ISSUE TITLE
feats.npy file not found

### ISSUE THREAD

**Issue by vokhidovhusan** [Xiangyu-CAS/AICity2020-VOC-ReID#23]
Hi
Thank you for your great job.
I am trying to run test with the trained model you provided but I can't find `feats.npy` file.

Following is the error I got:.

Traceback (most recent call last):
  File "./tools/aicity20/compute_distmat_from_feats.py", line 14, in <module>
    feat = np.load(src_dir + '/' + 'feats.npy')
  File "/home/husan/.virtualenvs/re-id/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './output/aicity20/0409-ensemble/ReOriID//feats.npy'

**Comment by Xiangyu-CAS** [comment]
Hi，feats.npy is generated by cmd: "bash ./scripts/aicity20/generate_matrix.sh", please refer to  AICity2020.md, the first step of Test and ensemble
