### ISSUE TITLE
compute_distmat_from_feats

### ISSUE THREAD

**Issue by vokhidovhusan** [Xiangyu-CAS/AICity2020-VOC-ReID#24]
@Xiangyu-CAS 
I want to ask you something if you can help me.
What does `compute_distmat_from_feats.py` do?
When I run `compute_distmat_from_feats.py` I have got this one (is something wrong with this output):

python ./tools/aicity20/compute_distmat_from_feats.py --src_dir ./output/aicity20/0409-ensemble/ReCamID/
./tools/aicity20/compute_distmat_from_feats.py:19: UserWarning: This overload of addmm_ is deprecated:
        addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
        addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  distmat.addmm_(1, -2, feat, feat.t())

**Comment by Xiangyu-CAS** [comment]
`compute_distmat_from_feats.py` is a script to compute similarity matrix. The main contribution of our work is to use sim matrix of orientation and cameras to increase accurcy.
