### ISSUE TITLE
Cosine similarity or euclidean distance?

### ISSUE THREAD

**Issue by jiaohere** [Xiangyu-CAS/AICity2020-VOC-ReID#28]
Hi,
I found that [euclidean distance](https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/master/lib/utils/post_process.py#L37) was used in your code to calculate distmat, while it was cosine similarity reported in your paper. As these two distance  are opposite in expressing similarity, why is the calculation formula for the fusion distance matrix in the code still the same as paper's:
original_dist = original_dist - 0.1 * ori_dist - 0.1 * cam_dist
Because the ori_distance and cam_distance should be penalty,  should "-" be changed to "+" ? But when I tried this so, the mAP on VeRi-776 decreased,  which is worse than the original distance. 
Looking forward to your reply, thanks!

**Comment by Xiangyu-CAS** [comment]
Hi，jiaohere，first of all,  when the feature is normalized, euclidean distance equals to cosine similarity, like in formulation :EuclideanDist = 2 - 2 * CosineSim. So it doesn't matter what kind of distance you use after normalization.  
Second, it should be "-', beacuse we are trying to reduce the weights of irrelavent features (orientation and camera view)

**Comment by jiaohere** [comment]
Hi Xiangyu,

Thank you very much for the reply! My point is that when using the cosine similarity, **larger** value means more similar, so we can use "original_dist = original_dist - 0.1 * ori_dist - 0.1 * cam_dist" to reduce the weights of irrelavent features.  But when the euclidean distance is used, **smaller** value means more similar, if we still want to reduce the irrelavent features, I think we should plus the ori_dist and cam_dist items. I'm still confused about this point. 

Hope for your explanation, thanks!

**Comment by jiaohere** [comment]
Hi Xiangyu, thank you very much for the explanation, I think I understand that.
