### ISSUE TITLE
Have you compared ResNeSt101 or ResNet101_ibn_a, which is better?

### ISSUE THREAD

**Issue by clw5180** [Xiangyu-CAS/AICity2020-VOC-ReID#3]
and is there ResNeSt101_ibn_a ? THanks!

**Comment by Xiangyu-CAS** [comment]
I didn't try 101 series. From our observation, ResNeSt50 outperforms ResNet50-ibn-a on all datasets, including market, veri and citiyflow. Thus, It's reasonable to assume that ResNeSt101 is better than ResNet101-ibn-a.

There is no pretrain model of ResNeSt with IBN structure. I think it would be great if the author Zhanghang can provide one, maybe we should open an issue at his repo?
