### ISSUE TITLE
请教下这个项目支持fp16+多卡么？

### ISSUE THREAD

**Issue by clw5180** [Xiangyu-CAS/AICity2020-VOC-ReID#4]
我看有人尝试在罗浩的baseline加过多卡和syncBN，但是掉点比较明显，不知是什么原因；看到前辈也加了 from apex.parallel import DistributedDataParallel as DDP 但是没有后续了

**Comment by Xiangyu-CAS** [comment]
不支持，等我数据量上百万了再改吧...很早的试过试过fp16 distributed training，训出来效果不太好就没管了...

**Comment by clw5180** [comment]
> 不支持，等我数据量上百万了再改吧...很早的试过试过fp16 distributed training，训出来效果不太好就没管了...

好的，多谢了

**Comment by Xiangyu-CAS** [comment]
@clw5180 知乎上luo hao和liaoxingyu也谈到了多卡训练的问题，他们一致表示多卡因为bn问题一定会掉点，即使改成syncBN也一样，所以为了精度，数据量连百万都没有就别用多卡了.....

**Comment by clw5180** [comment]
> @clw5180 知乎上luo hao和liaoxingyu也谈到了多卡训练的问题，他们一致表示多卡因为bn问题一定会掉点，即使改成syncBN也一样，所以为了精度，数据量连百万都没有就别用多卡了.....

多谢了，我昨天也在知乎问了下luo hao大佬

**Comment by clw5180** [comment]
> @clw5180 知乎上luo hao和liaoxingyu也谈到了多卡训练的问题，他们一致表示多卡因为bn问题一定会掉点，即使改成syncBN也一样，所以为了精度，数据量连百万都没有就别用多卡了.....

另外大佬参加天池的那个比赛了么，我看前排好多CAS的

**Comment by Xiangyu-CAS** [comment]
@clw5180 什么比赛...一脸懵逼....

**Comment by clw5180** [comment]
> @clw5180 什么比赛...一脸懵逼....

淘宝直播服装检索的一个比赛，目前正在用大佬的这个项目来做：）

**Comment by Xiangyu-CAS** [comment]
祝取得好成绩...那个我之前关注了下，貌似数据有300G？硬盘空间不够就不凑热闹了
