### ISSUE TITLE
Can you provide the Weakly Supervised Detection model please?

### ISSUE THREAD

**Issue by CLoudSnowMan** [Xiangyu-CAS/AICity2020-VOC-ReID#6]
I can't find aicity20/0326-search/augmix/best.pth

**Comment by Xiangyu-CAS** [comment]
Sorry, it has been deleted and can't be retrieved.... It's just a regular ReID model trained with Cityflow, you can train it from scratch

**Comment by Xiangyu-CAS** [comment]
Actually, you can just use detectron to crop images, it won't make much difference I think.
