### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by HanwenCao** [Xiangyu-CAS/AICity2020-VOC-ReID#8]
I was wondering which version of cv2 and python3.7 are you using? I tried python3.7.7 and it gives some unexpected errors when installing other required packages like yacs. Thank you!

**Comment by HanwenCao** [comment]
Is it possible to directly test the code without training using cpu-pytorch only?

**Comment by Xiangyu-CAS** [comment]
My python version is 3.7.4 while opencv version is 4.2.0.

I have provide the [link](https://drive.google.com/drive/folders/1W8nw3GEYyxZiuDSk_wdXTErHFxtfKfKI?usp=drive_open) to pretrain model, you can download it directly.

**Comment by HanwenCao** [comment]
> My python version is 3.7.4 while opencv version is 4.2.0.
> 
> I have provide the [link](https://drive.google.com/drive/folders/1W8nw3GEYyxZiuDSk_wdXTErHFxtfKfKI?usp=drive_open) to pretrain model, you can download it directly.

Thank you so much.@Xiangyu-CAS I tried to run` weakly_supervised_crop_aug.py ` to prepare data. However it seems that `/output/aicity20/0326-search/augmix/best.pth` is missing. 
It is not in the link. Where could I find it? Thank you.

**Comment by HanwenCao** [comment]
@Xiangyu-CAS  您好，请教您一下，
File "tools/aicity20/weakly_supervised_crop_aug.py", line 129, in main
    model.load_param(cfg.TEST.WEIGHT)
这个参数有提供吗？谢谢

**Comment by Xiangyu-CAS** [comment]
那个模型我不小心删了，就是初期用cityflow训练的一个ReID模型，用来做注意力crop图像，用detectron应该也能达到一样的效果。你可以用VeRi上的pretrain模型，或者自己从新用cityflow训练一个。

crop后的图像可以提供给你:
链接：https://pan.baidu.com/s/1DGMvhQ5mLZ4C7CS1aeaM-w 
提取码：vg71

**Comment by Xiangyu-CAS** [comment]
I
