### ISSUE TITLE
submit.py调用3次

### ISSUE THREAD

**Issue by HanwenCao** [Xiangyu-CAS/AICity2020-VOC-ReID#9]
https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/blob/master/scripts/aicity20/test.sh
在生成vehicle distance matrix的时候，submit.py被调用3次，分别是“50”“101”“next”。
请问为什么需要这样做啊？谢谢！

**Comment by Xiangyu-CAS** [comment]
因为是多模型融合，融合了50，101，next 共3个模型，从生成三个distmat然后取平均

**Comment by HanwenCao** [comment]
> 因为是多模型融合，融合了50，101，next 共3个模型，从生成三个distmat然后取平均

Simply ensemble models with different backbones does not benefit a lot, it approximately improves 2% on mAP at the cost of tripling training processes and model sizes, which totally not worth it.
我刚发现您的论文提到了这个。请问是说这么做不值得吗？

**Comment by Xiangyu-CAS** [comment]
嗯，是的，多模型融合主要带来的是参数上的增益，并没有学到更多差异较大的信息，所以三个模型才提高2%，但因为这个是竞赛，大家都堆多模型，所以我也不得不做。如果按照论文里的思路，一个模型学vehicle，一个模型学orientation，一个模型学camera，这三个模型分别学习了不同的信息，组合起来就有10%的增益

**Comment by HanwenCao** [comment]
> 嗯，是的，多模型融合主要带来的是参数上的增益，并没有学到更多差异较大的信息，所以三个模型才提高2%，但因为这个是竞赛，大家都堆多模型，所以我也不得不做。如果按照论文里的思路，一个模型学vehicle，一个模型学orientation，一个模型学camera，这三个模型分别学习了不同的信息，组合起来就有10%的增益


明白了，感谢指点。请问这三个文件对应的生成代码在哪啊？

'./output/aicity20/0409-ensemble/r50-320-circle/distmat.npy',
'./output/aicity20/0409-ensemble/next101-320-circle/distmat.npy',
'./output/aicity20/0409-ensemble/r101-320-circle/distmat.npy'

**Comment by Xiangyu-CAS** [comment]
```
python tools/aicity20/submit.py --config_file='configs/aicity20.yml' \
MODEL.DEVICE_ID "('0')" \
MODEL.NAME "('resnet50_ibn_a')" \
MODEL.MODEL_TYPE "baseline" \
DATASETS.TRAIN "('aicity20',)" \
DATASETS.TEST "('aicity20',)" \
DATASETS.ROOT_DIR "('/home/zxy/data/ReID/vehicle')" \
MODEL.PRETRAIN_CHOICE "('self')" \
INPUT.SIZE_TRAIN '([320, 320])' \
INPUT.SIZE_TEST '([320, 320])' \
TEST.QUERY_EXPANSION True \
TEST.DO_RERANK False \
TEST.TRACK_AUG False \
TEST.RERANK_PARAM "([50, 15, 0.5])" \
TEST.FLIP_TEST True \
TEST.TRACK_RERANK False \
TEST.WRITE_RESULT True \
TEST.WEIGHT "('./output/aicity20/0408-ensemble/r50-320/best.pth')"
```
把 TEST.WRITE_RESULT =  True的时候，就会输出distmat
